DROP TABLE IF EXISTS users, categories, events, compilations, compilation_events CASCADE;

CREATE TABLE IF NOT EXISTS users (
id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
email varchar(256)                           NOT NULL UNIQUE,
name varchar(32)                                     NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
name varchar(32)                             NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
id INT             GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
annotation varchar(512)                                         NOT NULL,
category_id INT REFERENCES categories (id) ON DELETE NO ACTION  NOT NULL,
description varchar(2048)                                       NOT NULL,
event_date TIMESTAMP WITHOUT TIME ZONE                          NOT NULL,
location_lat FLOAT                                              NOT NULL,
location_lon FLOAT                                              NOT NULL,
paid boolean                                      NOT NULL DEFAULT false,
participant_limit INT                                 NOT NULL DEFAULT 0,
confirmed_requests INT,
request_moderation boolean                         NOT NULL DEFAULT true,
title varchar(128)                                              NOT NULL,
initiator_id INT         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
state varchar(256)                             NOT NULL DEFAULT 'PENDING',
created_on TIMESTAMP                           WITHOUT TIME ZONE NOT NULL,
published_on TIMESTAMP                                  WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS compilations (
id INT      GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
pinned boolean                            NOT NULL DEFAULT false,
title varchar(64)                                       NOT NULL
);

CREATE TABLE IF NOT EXISTS requests (
id INT                   GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
event_id INT             NOT NULL REFERENCES events (id) ON DELETE CASCADE,
requester_id INT          NOT NULL REFERENCES users (id) ON DELETE CASCADE,
status varchar(256)                             NOT NULL DEFAULT 'PENDING',
created_date TIMESTAMP                           WITHOUT TIME ZONE NOT NULL,
CONSTRAINT requests_pk PRIMARY KEY (requester_id, event_id)
);

CREATE TABLE IF NOT EXISTS compilation_events (
compilation_id INT REFERENCES compilations (id) ON DELETE CASCADE NOT NULL,
event_id INT              REFERENCES events (id) ON DELETE CASCADE NOT NULL,
PRIMARY KEY(compilation_id, event_id)
);